name: Deploy to Railway
on:
  schedule:
    - cron: 0 */12 * * *
  workflow_dispatch:
jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      # Checks-out your repository under $GITHUB_WORKSPACE, so your job can access it
      - uses: actions/checkout@v3
      
      - name: Deploy to Railway
        run: |
          apt-get update -y && apt-get install -y curl
          curl -fsSL https://railway.app/install.sh | sh
          RAILWAY_TOKEN=${{ secrets.RAILWAY_TOKEN }} railway up ${{ github.workspace }}
